apiVersion: v1
kind: Service
metadata:
  name: { { include "postgresql.fullname" . } }
  labels:
    app: { { include "postgresql.fullname" . } }
spec:
  type: { { .Values.service.type } }
  selector:
    app: { { include "postgresql.fullname" . } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
      protocol: TCP
      name: postgres
