apiVersion: v1
kind: Service
metadata:
  name: {{ default .Values.deploymentName (include "helm-recype.fullname" .) }}-service
  labels:
    app: {{ default .Values.deploymentName (include "helm-recype.fullname" .) }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ default .Values.deploymentName (include "helm-recype.fullname" .) }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
